# Generated by Django 6.0.7 on 2026-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='go', upload_to=''),
            preserve_default=False,
        ),
    ]
