# Generated by Django 6.0.7 on 2026-07-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Erledigt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=6, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=6, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, verbose_name='Fällig am'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert'),
        ),
    ]
