# Generated by Django 6.0.7 on 2026-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('66c5cc', 'türkis'), ('f6cf71', 'gelb'), ('f89c74', 'orange'), ('dcb0f2', 'lila'), ('87c55f', 'grün'), ('9eb9f3', 'blau'), ('fe88b1', 'rosa'), ('b3b3b3', 'grau')], default='b3b3b3', max_length=6, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('66c5cc', 'türkis'), ('f6cf71', 'gelb'), ('f89c74', 'orange'), ('dcb0f2', 'lila'), ('87c55f', 'grün'), ('9eb9f3', 'blau'), ('fe88b1', 'rosa'), ('b3b3b3', 'grau')], default='b3b3b3', max_length=6, verbose_name='Farbe'),
        ),
    ]
