# Generated by Django 6.0.7 on 2026-08-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(choices=[('JE', 'Jede Elektro'), ('EW', 'Elektro Wolff')], default='EW', max_length=50, verbose_name='Firma'),
        ),
    ]
