# Generated by Django 6.0.7 on 2026-07-23 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
