# Generated by Django 6.0.7 on 2026-07-23 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyplan',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start')),
                ('end_date', models.DateTimeField(verbose_name='Ende')),
                ('description', models.TextField(blank=True)),
                ('employees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Zuweisung',
                'verbose_name_plural': 'Zuweisungen',
                'ordering': ['-end_date'],
                'get_latest_by': ['-end_date', '-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='DailyAssignment',
        ),
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
    ]
